name: Gegenlicht
favicon: null
layout_spectrum: 0.87862
typography_spectrum: 0.3751002037897706
title: Gegenlicht.Pictures - Photography Showroom
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
